## Config file for creating instances of DetImage image class for a basic CCD detector
## The DetImage instance is designed to contain the outputs of a SINGLE detector (not mosaic).
## The flexibility provided by YAML allows instantiating image(s) from one FITS file with one extension that has all the detectors/outputs,
## OR from multiple FITS extensions, one per detector/output, OR from multiple FITS files, one per detector/output.
## The config structure should describe what's contained per FITS file.

## The following example describes a single CCD detector with two outputs (channels) that are read out from the same FITS extension.
## The data for each output is defined by a slice of the FITS extension (ext_slice), and the location of that data in the full DetImage data array is also defined by a slice (data_slice).
---
description: Basic single CCD detector, two channels # optional description
detector_type: CCD # optional, detector type, e.g., CCD, CMOS, H2RG, etc.
detector_output_class: CCDOutput # REQUIRED, use correct class name here for the detector type

objects: # REQUIRED, list of image objects per input (file or array)
  - name: 'det_1' # REQUIRED, ID for this image instance
    class: DetImage # REQUIRED, image class name, DetImage is the provided base class for 2D images
    filename_format: '*.fits*'  # Use wildcard to pattern match filename if needed
    properties: # REQUIRED, properties of the detector
      x_size: 2048
      y_size: 4096
      saturation_level: 65535  # ADU
      pixel_size: 0.015  # mm

    # Slice definition is [start, stop), stop is exclusive
    outputs: # REQUIRED, list of outputs
      - id: 'chan_1' # REQUIRED, ID for this output
        ext_id: 1 # REQUIRED, FITS extension that contains this output's data
        ext_slice: [!slice [0, 4096], !slice [0, 1024]]  # REQUIRED, Slice in ext_id corresponding to this output
        data_slice: [!slice [0, 4096], !slice [0, 1024]] # REQUIRED, Slice of DetImage array to put the above into
        serial_prescan: !slice [0, 20] # 20 prescan columns (indices w.r.t. data_slice)
        serial_overscan: !slice [1004, 1024] # 20 overscan columns (indices w.r.t. data_slice)
        parallel_prescan: !slice [0, 20] # 20 prescan rows (indices w.r.t. data_slice)
        parallel_overscan: !slice [4076, 4096] # 20 overscan rows (indices w.r.t. data_slice)
        parallel_axis: 'y' # Axis in the data array aligned to parallel readout direction
        readout_pixel: [0, 0]  # For readout direction (assumed to be away from this pixel in both axes)
        gain: 1.0  # electrons/ADU
        read_noise: 5.0  # electrons
        bias_level: 1000  # ADU
      - id: 'chan_2'
        ext_id: 2
        ext_slice: [!slice [0, 4096], !slice [0, 1024]] #(right half)
        data_slice: [!slice [0, 4096], !slice [1024, 2048]]  #(right half)
        serial_prescan: !slice [2048, 2027] # since readout pixel is at top right
        serial_overscan: !slice [1044, 1023]
        parallel_prescan: !slice [0, 20]
        parallel_overscan: !slice [4076, 4096]
        parallel_axis: 'y'
        readout_pixel: [0, 2047]  # (top right)
        gain: 1.0  # electrons/ADU
        read_noise: 5.0  # electrons
        bias_level: 1000  # ADU
    focal_plane_position:
      x_cen: 0.0  # mm
      y_cen: 0.0  # mm
      angle: 0.0  # rotate by this angle (degrees)
      flip_x: false  # boolean, flip x-axis
      flip_y: false  # boolean, flip y-axis



