# toml
[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "eregion"
version = "0.1.0"
description = "Detector characterization framework"
readme = "README.md"
requires-python = ">=3.12,<3.14"
authors = [{ name = "Yashvi-Sharma", email = "yssharma@caltech.edu" },
	   { name = "Dan Weatherill", email = "dweather@caltech.edu" },
	   { name = "Prakriti Gupta", email = "pgupta@caltech.edu" }]
license = { text = "MIT" }

dependencies = [
    "numpy>=1.26",
    "pandas>=2.3.3",
    "xarray>=2026.1.0",
    "astropy>=7.0",
    "matplotlib>=3.9",
    "glob2>=0.7",
    "prefect>=2.15.0",
    "pyyaml>=6.0.3",
    "pydantic>=2.12.4",
    "joblib>=1.5.3",
    "scipy>=1.14",
    "uncertainties>=3.2.3",
    "pint >= 0.25.3",
    "pydantic-pint >=0.4"
]

[project.optional-dependencies]
dev = [
    "black>=24.0",
    "ipykernel>=6.28",
    "flake8",
]
test = [
    "pytest>=7.0",
]

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
where = ["src"]
include = ["eregion*"]

[tool.hatch.envs.default]
python = "3.12"
