# toml
[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "eregion"
version = "0.1.0"
description = "Detector characterization framework"
readme = "README.md"
requires-python = ">=3.10,<3.14"
authors = [{ name = "Yashvi-Sharma" }]
license = { text = "MIT" }

dependencies = [
    "numpy>=1.26",
    "pandas>=2.0",
    "xarray>=2023.5.0",
    "astropy>=5.0",
    "glob2>=0.7",
    "prefect>=2.15.0",
]

[project.optional-dependencies]
dev = [
    "black>=24.0",
    "ipykernel>=6.28",
    "flake8",
]
test = [
    "pytest>=7.0",
]

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
where = ["."]
include = ["core*", "datamodels*", "pipeline*", "tasks*"]