from typing import Optional, Iterable, Generator

import xarray
import numpy as np
from joblib import Parallel, delayed


from eregion.tasks import LazyTask
from eregion.tasks.ptc import PTCResult
from eregion.datamodels import DetImage, ImageBundle, CCDOutput

from eregion.core.image_stats import do_statistics
from eregion.utils.dangerous_magic import pack_argument_helper


class TDIExtractPTC(LazyTask):
    task_result = PTCResult

    def __init__(self,
                 groupby_keys: Iterable[str],
                 name: Optional[str] = None):

        self.groupby_keys = groupby_keys
            
        newkwargs = pack_argument_helper(selfarg=self)
        super().__init__(**newkwargs)

    def lazy_run(self, images: ImageBundle | Iterable[DetImage]) -> Generator[PTCResult, None, None]:

        if not isinstance(images, ImageBundle):
            images = ImageBundle(images)

        groups = images.groupby(by=self.groupby_keys, sort=False)

        #TODO: implement parallel or not needed? Wait for new Task design and don't bother?
        results = Parallel(n_jobs = self.n_jobs)(
            delayed(self._process_group)(ImageBundle.from_dataframe(g)) for k, g in groups)

        return results
        


    def _process_group(self, images: ImageBundle[DetImage]):
        base_info = {k : images.list[k][0] for k in self.groupby_keys}

        stats = []
        
        for i, img in enumerate(images):
            for outputid, output in img.outputs.items():
                outstat = base_info | {"output" : outputid}
                #in a TDI curve, exptime is proxied by the parallel axis coordinate
                im, _ = output.get_image_region()
                etime_arr: np.ndarray = im[output.parallel_axis].data
                outstat |= self.tdi_stats(output)

                self.logger.debug("len(etime_arr) = %d, len(outstat[mean])= %d", len(etime_arr), len(outstat["mean"]))

                assert len(etime_arr) == len(outstat["mean"])
                stats.append(outstat)

        return stats
    
    def tdi_stats(self, output: CCDOutput):
        """Do simple TDI stats on a single output.
        TDI statistics are always done along the serial (because the TDI curve is generated by
        keeping the light on while doing the parallel transfer.

        This function assumes an already overscan and bias subtracted image
       
        """

        im, masks = output.get_image_region(return_masks=True)

        #TODO: consider convenience function in DetImage that combines masks properly
        if masks is not None:
            totmask = xarray.zeros_like(masks[0])
            for mask in masks:
                totmask |= mask
        else:
            totmask = None
        ma = np.ma.MaskedArray(data=im, mask=totmask)
        stats = do_statistics(ma, axis=output.serial_axint)
        
        
        return stats
        
