# This is an example pipeline flow configuration for creating a master bias frame

debug: false
pipelines:
  - name: calib_flow
    description: Pipeline flow to create a master bias frame from bias images
    lazy: false
    nodes:
      - name: image_creator
        task: tasks.imagegen.ImageCreator
        init:
          params:
            detector_config: ${DETECTOR_CONFIG}
        run:
          params:
            input_source: r"\${INPUT_SOURCE}/*.fits"
            identifier_func: tasks.custom.guess_image_type_from_filename
            fitsloader_func: tasks.custom.load_image_fits
      - name: make_master_bias
        task: tasks.calibration.MasterBias
        init:
          params:
            method: "median"
        run:
          inputs:
            images: calib_flow.image_creator.data('type == "bias"')
        depends_on: [calib_flow.image_creator]

  - name: preproc_flow
    description: Example pre-processing pipeline flow
    lazy: false
    nodes:
      - name: bias_subtraction
        task: tasks.preprocessing.BiasSubtraction
        init:
          params:
            only_image_areas: true
        run:
          inputs:
            images: calib_flow.image_creator.data('type == "flat"')
            master_bias: calib_flow.make_master_bias.master_bias
        depends_on: [calib_flow.image_creator, calib_flow.make_master_bias]

      - name: overscan_subtraction
        task: tasks.preprocessing.ScanSubtraction
        init:
          params:
            which_scan: 'serial_overscan'
            method: 'median_by_axis'
        run:
          inputs:
            images: preproc_flow.bias_subtraction.data.flat
        depends_on: [preproc_flow.bias_subtraction]

      - name: badpixel_masking
        task: tasks.preprocessing.SigmaClipMasking
        run:
          inputs:
            images: preproc_flow.overscan_subtraction.data.flat
        depends_on: [preproc_flow.overscan_subtraction]
