# This is an example pipeline flow configuration for creating a master bias frame

debug: false
pipelines:
  - name: masterbias_flow
    description: Load biases, subtract overscan, and create master biases
    lazy: false
    nodes:
      - name: bias_creator
        task: eregion.tasks.imagegen.ImageCreator
        init:
          params:
            detector_config: ${DETECTOR_CONFIG}
        run:
          params:
            input_source: ${BIAS_INPUT_SOURCE}
            identifier_func: eregion.tasks.custom.guess_image_type_from_filename_DEIMOS
            fileloader_func: eregion.tasks.custom.load_image_fits_DEIMOS
            data_on_demand: true

      - name: overscan_sub
        task: eregion.tasks.preprocessing.ScanSubtraction
        init:
          params:
            which_scan: 'serial_overscan'
            method: 'median_by_axis'
            trim_start: 6
        run:
          inputs:
            images: masterbias_flow.bias_creator.data('type == "bias"')
        depends_on: [masterbias_flow.bias_creator]

      - name: make_master_bias
        task: eregion.tasks.calibration.MasterBias
        init:
          params:
            groupby_keys: ["det_id"]
            method: "median"
        run:
          inputs:
            images: masterbias_flow.overscan_sub.data('type == "bias"')
        depends_on: [masterbias_flow.overscan_sub]

      - name: cleanup_0
        task: eregion.tasks.bookkeeping.DeleteResult
        run:
          inputs:
            result: masterbias_flow.bias_creator

      - name: cleanup_1
        task: eregion.tasks.bookkeeping.DeleteResult
        run:
          inputs:
            result: masterbias_flow.overscan_sub

  - name: ptc_flow
    description: Flow for PTC processing
    lazy: true
    source: ptc_flow.creator
    nodes:
      - name: creator
        task: eregion.tasks.imagegen.ImageCreator
        init:
          params:
            detector_config: ${DETECTOR_CONFIG}
            max_batch_size: 32
        run:
          params:
            input_source: ${INPUT_SOURCE}
            identifier_func: eregion.tasks.custom.guess_image_type_from_filename_DEIMOS
            fileloader_func: eregion.tasks.custom.load_image_fits_DEIMOS
            data_on_demand: true

      - name: overscan_sub
        task: eregion.tasks.preprocessing.ScanSubtraction
        init:
          params:
            which_scan: 'serial_overscan'
            method: 'median_by_axis'
            trim_start: 6
        run:
          inputs:
            images: ptc_flow.creator.data
        depends_on: [ptc_flow.creator]

      - name: badpixel_masking
        task: eregion.tasks.preprocessing.SigmaClipMasking
        run:
          inputs:
            images: ptc_flow.overscan_sub.data
        depends_on: [ptc_flow.overscan_sub]

      - name: bias_subtraction
        task: eregion.tasks.preprocessing.BiasSubtraction
        init:
          params:
            only_image_area: true
        run:
          inputs:
            images: ptc_flow.badpixel_masking.data
            master_bias: masterbias_flow.make_master_bias.master_bias
        depends_on: [ptc_flow.badpixel_masking, masterbias_flow.make_master_bias]

      - name: make_ptc_table
        task: eregion.tasks.ptc.PTC
        init:
          params:
            groupby_keys: ["det_id", "exptime"]
            exptime_key: "exptime"
            psd_size: 9
        run:
          inputs:
            images: ptc_flow.bias_subtraction.data
        depends_on: [ptc_flow.bias_subtraction]

      - name: save
        task: eregion.tasks.bookkeeping.SaveResult
        run:
          inputs:
            # A list of references is resolved into a list of TaskResults, in this order
            task_results:
              - masterbias_flow.make_master_bias
              - ptc_flow.make_ptc_table
          params:
            output_dir: ${OUTPUT_DIR}
        depends_on: [masterbias_flow.make_master_bias, ptc_flow.make_ptc_table]

