# This is an example pipeline flow configuration for creating a master bias frame

debug: false
pipelines:
  - name: calib_flow
    description: Pipeline flow to create a master bias frame from bias images
    lazy: false
    nodes:
      - name: image_creator
        task: tasks.imagegen.ImageCreator
        init:
          params:
            detector_config: "/Users/yashvi/Desktop/Detector Characterization Tools/eregion/eregion/configs/detectors/deimos_singledet.yaml"
        run:
          params:
            input_source: "/Users/yashvi/Desktop/Detector Characterization Tools/DTU_dettest/DTU_singledet_acceptance/PTC/SCI/20250812-101350/*_bias_*.fits"
            identifier_func: tasks.custom.guess_image_type_from_filename_DEIMOS

      - name: master_bias
        task: tasks.calibration.MasterBias
        init:
          params:
            method: "median"
        run:
          inputs:
            bias_images: calib_flow.image_creator.data.bias
        depends_on: [calib_flow.image_creator]

  - name: preproc_flow
    description: Example pre-processing pipeline flow
    lazy: false
    nodes:
      - name: image_creator
        task: tasks.imagegen.ImageCreator
        init:
          params:
            detector_config: "/Users/yashvi/Desktop/Detector Characterization Tools/eregion/eregion/configs/detectors/deimos_singledet.yaml"
        run:
          params:
            input_source: "/Users/yashvi/Desktop/Detector Characterization Tools/DTU_dettest/DTU_singledet_acceptance/PTC/SCI/20250812-101350/*flat_0.000*.fits"
            identifier_func: tasks.custom.guess_image_type_from_filename_DEIMOS

      - name: bias_subtraction
        task: tasks.preprocessing.BiasSubtraction
        init:
          inputs:
            master_biases: calib_flow.master_bias.data.master_biases
        run:
          inputs:
            images: preproc_flow.image_creator.data.flat
        depends_on: [preproc_flow.image_creator, calib_flow.master_bias]

      - name: overscan_subtraction
        task: tasks.preprocessing.ScanSubtraction
        init:
          params:
            which_scan: 'serial_overscan'
            method: 'median_by_axis'
        run:
          inputs:
            images: preproc_flow.bias_subtraction.data.flat
        depends_on: [preproc_flow.bias_subtraction]

      - name: badpixel_masking
        task: tasks.preprocessing.SigmaClipMasking
        run:
          inputs:
            images: preproc_flow.overscan_subtraction.data.flat
        depends_on: [preproc_flow.overscan_subtraction]
