## NEW DEIMOS science CCD config, first pass version
## FITS with 1 extension containing full focal plane image with 8 detectors -> 8 DetImage instances to be created
---
description: DEIMOS CCD detector array, 8 detectors with two channel readout each
detector_type: CCD
detector_output_class: CCDOutput

objects:
  - name: 'det_1'
    class: DetImage
    filename_format: '*.fits*'
    properties:
      x_size: 2188
      y_size: 4125
      saturation_level: 65535  # ADU
      pixel_size: 0.015  # mm
    outputs:
      - id: 'E1'
        ext_id: 0
        ext_slice: [!slice [8249, 4124], !slice [0, 1094]]
        data_slice: [!slice [0, 4125], !slice [0, 1094]]
        serial_prescan: !slice [0, 50]
        serial_overscan: !slice [1074, 1094]
        parallel_prescan: !slice [0, 1]
        parallel_overscan: !slice [4105, 4125]
        parallel_axis: 'y'
        readout_pixel: [0, 0]
      - id: 'F1'
        ext_id: 0
        ext_slice: [!slice [8249, 4124], !slice [1094, 2188]]
        data_slice: [!slice [0, 4125], !slice [1094, 2188]]
        serial_prescan: !slice [2187, 2137]
        serial_overscan: !slice [1113, 1093]
        parallel_prescan: !slice [0, 1]
        parallel_overscan: !slice [4105, 4125]
        parallel_axis: 'y'
        readout_pixel: [0, 2187]
    focal_plane_position:
      x_cen: -49.23  # mm
      y_cen: 30.9375  # mm
      angle: 0.0  # degrees
      flip_x: false
      flip_y: true

  - name: 'det_2'
    class: DetImage
    filename_format: '*.fits*'  # Use wildcard to indicate the filename
    properties:
      x_size: 2188
      y_size: 4125
      saturation_level: 65535  # ADU
      pixel_size: 0.015  # mm
    outputs:
      - id: 'E2'
        ext_id: 0
        ext_slice: [!slice [8249, 4124], !slice [2188, 3282]]
        data_slice: [!slice [0, 4125], !slice [0, 1094]]
        serial_prescan: !slice [0, 50]
        serial_overscan: !slice [1074, 1094]
        parallel_prescan: !slice [0, 1]
        parallel_overscan: !slice [4105, 4125]
        parallel_axis: 'y'
        readout_pixel: [0, 0]
      - id: 'F2'
        ext_id: 0
        ext_slice: [!slice [8249, 4124], !slice [3282, 4376]]
        data_slice: [!slice [0, 4125], !slice [1094, 2188]]
        serial_prescan: !slice [2187, 2137]
        serial_overscan: !slice [1113, 1093]
        parallel_prescan: !slice [0, 1]
        parallel_overscan: !slice [4105, 4125]
        parallel_axis: 'y'
        readout_pixel: [0, 2187]
    focal_plane_position:
      x_cen: -16.41  # mm
      y_cen: 30.9375  # mm
      angle: 0.0  # degrees
      flip_x: false
      flip_y: true

  - name: 'det_3'
    class: DetImage
    filename_format: '*.fits*'  # Use wildcard to indicate the filename
    properties:
      x_size: 2188
      y_size: 4125
      saturation_level: 65535  # ADU
      pixel_size: 0.015  # mm
    outputs:
      - id: 'E3'
        ext_id: 0
        ext_slice: [!slice [8249, 4124], !slice [4376, 5470]]
        data_slice: [!slice [0, 4125], !slice [0, 1094]]
        serial_prescan: !slice [0, 50]
        serial_overscan: !slice [1074, 1094]
        parallel_prescan: !slice [0, 1]
        parallel_overscan: !slice [4105, 4125]
        parallel_axis: 'y'
        readout_pixel: [0, 0]
      - id: 'F3'
        ext_id: 0
        ext_slice: [!slice [8249, 4124], !slice [5470, 6564]]
        data_slice: [!slice [0, 4125], !slice [1094, 2188]]
        serial_prescan: !slice [2187, 2137]
        serial_overscan: !slice [1113, 1093]
        parallel_prescan: !slice [0, 1]
        parallel_overscan: !slice [4105, 4125]
        parallel_axis: 'y'
        readout_pixel: [0, 2187]
    focal_plane_position:
      x_cen: 16.41  # mm
      y_cen: 30.9375  # mm
      angle: 0.0  # degrees
      flip_x: false
      flip_y: true

  - name: 'det_4'
    class: DetImage
    filename_format: '*.fits*'  # Use wildcard to indicate the filename
    properties:
      x_size: 2188
      y_size: 4125
      saturation_level: 65535  # ADU
      pixel_size: 0.015  # mm
    outputs:
      - id: 'E4'
        ext_id: 0
        ext_slice: [!slice [8249, 4124], !slice [6564, 7658]]
        data_slice: [!slice [0, 4125], !slice [0, 1094]]
        serial_prescan: !slice [0, 50]
        serial_overscan: !slice [1074, 1094]
        parallel_prescan: !slice [0, 1]
        parallel_overscan: !slice [4105, 4125]
        parallel_axis: 'y'
        readout_pixel: [0, 0]
      - id: 'F4'
        ext_id: 0
        ext_slice: [!slice [8249, 4124], !slice [7658, 8752]]
        data_slice: [!slice [0, 4125], !slice [1094, 2188]]
        serial_prescan: !slice [2187, 2137]
        serial_overscan: !slice [1113, 1093]
        parallel_prescan: !slice [0, 1]
        parallel_overscan: !slice [4105, 4125]
        parallel_axis: 'y'
        readout_pixel: [0, 2187]
    focal_plane_position:
      x_cen: 49.23  # mm
      y_cen: 30.9375  # mm
      angle: 0.0  # degrees
      flip_x: false
      flip_y: true

  - name: 'det_5'
    class: DetImage
    filename_format: '*.fits*'  # Use wildcard to indicate the filename
    properties:
      x_size: 2188
      y_size: 4125
      saturation_level: 65535  # ADU
      pixel_size: 0.015  # mm
    outputs:
      - id: 'E5'
        ext_id: 0
        ext_slice: [!slice [0, 4125], !slice [8751, 7657]]
        data_slice: [!slice [0, 4125], !slice [0, 1094]]
        serial_prescan: !slice [0, 50]
        serial_overscan: !slice [1074, 1094]
        parallel_prescan: !slice [0, 1]
        parallel_overscan: !slice [4105, 4125]
        parallel_axis: 'y'
        readout_pixel: [0, 0]
      - id: 'F5'
        ext_id: 0
        ext_slice: [!slice [0, 4125], !slice [7657, 6563]]
        data_slice: [!slice [0, 4125], !slice [1094, 2188]]
        serial_prescan: !slice [2187, 2137]
        serial_overscan: !slice [1113, 1093]
        parallel_prescan: !slice [0, 1]
        parallel_overscan: !slice [4105, 4125]
        parallel_axis: 'y'
        readout_pixel: [0, 2187]
    focal_plane_position:
      x_cen: 49.23  # mm
      y_cen: -30.9375  # mm
      angle: 0.0  # degrees
      flip_x: true
      flip_y: false

  - name: 'det_6'
    class: DetImage
    filename_format: '*.fits*'  # Use wildcard to indicate the filename
    properties:
      x_size: 2188
      y_size: 4125
      saturation_level: 65535  # ADU
      pixel_size: 0.015  # mm
    outputs:
      - id: 'E6'
        ext_id: 0
        ext_slice: [!slice [0, 4125], !slice [6563, 5469]]
        data_slice: [!slice [0, 4125], !slice [0, 1094]]
        serial_prescan: !slice [0, 50]
        serial_overscan: !slice [1074, 1094]
        parallel_prescan: !slice [0, 1]
        parallel_overscan: !slice [4105, 4125]
        parallel_axis: 'y'
        readout_pixel: [0, 0]
      - id: 'F6'
        ext_id: 0
        ext_slice: [!slice [0, 4125], !slice [5469, 4375]]
        data_slice: [!slice [0, 4125], !slice [1094, 2188]]
        serial_prescan: !slice [2187, 2137]
        serial_overscan: !slice [1113, 1093]
        parallel_prescan: !slice [0, 1]
        parallel_overscan: !slice [4105, 4125]
        parallel_axis: 'y'
        readout_pixel: [0, 2187]
    focal_plane_position:
      x_cen: 16.41  # mm
      y_cen: -30.9375 # mm
      angle: 0.0  # degrees
      flip_x: true
      flip_y: false

  - name: 'det_7'
    class: DetImage
    filename_format: '*.fits*'  # Use wildcard to indicate the filename
    properties:
      x_size: 2188
      y_size: 4125
      saturation_level: 65535  # ADU
      pixel_size: 0.015  # mm
    outputs:
      - id: 'E7'
        ext_id: 0
        ext_slice: [!slice [0, 4125], !slice [4375, 3281]]
        data_slice: [!slice [0, 4125], !slice [0, 1094]]
        serial_prescan: !slice [0, 50]
        serial_overscan: !slice [1074, 1094]
        parallel_prescan: !slice [0, 1]
        parallel_overscan: !slice [4105, 4125]
        parallel_axis: 'y'
        readout_pixel: [0, 0]
      - id: 'F7'
        ext_id: 0
        ext_slice: [!slice [0, 4125], !slice [3281, 2187]]
        data_slice: [!slice [0, 4125], !slice [1094, 2188]]
        serial_prescan: !slice [2187, 2137]
        serial_overscan: !slice [1113, 1093]
        parallel_prescan: !slice [0, 1]
        parallel_overscan: !slice [4105, 4125]
        parallel_axis: 'y'
        readout_pixel: [0, 2187]
    focal_plane_position:
      x_cen: -16.41  # mm
      y_cen: -30.9375  # mm
      angle: 0.0  # degrees
      flip_x: true
      flip_y: false

  - name: 'det_8'
    class: DetImage
    filename_format: '*.fits*'  # Use wildcard to indicate the filename
    properties:
      x_size: 2188
      y_size: 4125
      saturation_level: 65535  # ADU
      pixel_size: 0.015  # mm
    outputs:
      - id: 'E8'
        ext_id: 0
        ext_slice: [!slice [0, 4125], !slice [2187, 1093]]
        data_slice: [!slice [0, 4125], !slice [0, 1094]]
        serial_prescan: !slice [0, 50]
        serial_overscan: !slice [1074, 1094]
        parallel_prescan: !slice [0, 1]
        parallel_overscan: !slice [4105, 4125]
        parallel_axis: 'y'
        readout_pixel: [0, 0]
      - id: 'F8'
        ext_id: 0
        ext_slice: [!slice [0, 4125], !slice [1093, -1]]
        data_slice: [!slice [0, 4125], !slice [1094, 2188]]
        serial_prescan: !slice [2187, 2137]
        serial_overscan: !slice [1113, 1093]
        parallel_prescan: !slice [0, 1]
        parallel_overscan: !slice [4105, 4125]
        parallel_axis: 'y'
        readout_pixel: [0, 2187]
    focal_plane_position:
      x_cen: -49.23  # mm
      y_cen: -30.9375  # mm
      angle: 0.0  # degrees
      flip_x: true
      flip_y: false



